# Generated by Django 5.2.7 on 2025-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
