# Generated by Django 5.2.7 on 2025-11-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0002_voluntario_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='disponibilidade',
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
    ]
