# Generated by Django 5.2.7 on 2025-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0003_remove_voluntario_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='link_externo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
    ]
