# Generated by Django 5.2.7 on 2025-11-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0004_alter_noticia_options_noticia_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='integrantes/'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
