# Generated by Django 5.2.8 on 2025-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0006_trilhas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilhas',
            name='autor',
        ),
        migrations.AlterField(
            model_name='trilhas',
            name='data_publicacao',
            field=models.DateTimeField(),
        ),
    ]
