# Generated by Django 5.2.8 on 2025-11-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0007_remove_trilhas_autor_alter_trilhas_data_publicacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trilhas',
            new_name='Trilha',
        ),
    ]
