# Generated by Django 5.2.7 on 2025-11-14 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0008_rename_trilhas_trilha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Digite um telefone válido. Ex: (21) 98765-4321', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
