# Generated by Django 5.2.7 on 2025-11-14 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0009_alter_voluntario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='nome',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e espaços.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ\\s]+$')]),
        ),
    ]
