# Generated by Django 5.2.7 on 2025-11-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0010_alter_voluntario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
