# Generated by Django 5.2.7 on 2025-11-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0011_alter_voluntario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='autor',
            new_name='criado_por',
        ),
    ]
