# Generated by Django 5.2.7 on 2025-11-16 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0012_rename_autor_noticia_criado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='criado_por',
            new_name='autor',
        ),
    ]
