# Generated by Django 5.2.7 on 2025-11-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0013_rename_criado_por_noticia_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='autor',
            new_name='criado_por',
        ),
    ]
