# Generated by Django 5.2.7 on 2025-11-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0015_trilha_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(),
        ),
    ]
