# Generated by Django 5.2.7 on 2025-11-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuca', '0016_alter_noticia_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='funcao',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='imagem',
            field=models.ImageField(upload_to='integrantes/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link_externo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='imagem',
            field=models.ImageField(upload_to='trilhas/'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='link_externo',
            field=models.URLField(),
        ),
    ]
